title: Parker T. Robbins
logo: /assets/img/logo.png
description: Research assistant and aspiring linguistics graduate student
show_downloads: true
google_analytics: UA-179154706-1
theme: jekyll-theme-minimal
