title: Parker T. Robbins
logo: /assets/img/parker_robbins.png
description: Research assistant and aspiring linguistics graduate student
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
